new api
yergoff/marvel-api pull request #1
Opened 2022-05-30 17:49 UTC by yergoff

2022-05-30 18:13 UTC, ssstoyanov requested changes

2022-05-30 18:13 UTC, ssstoyanov commented on pom.xml
> +    <description>Marvel</description>
Именование можно использовать любое

Это необходимо чтобы просто идентифицировать пакет

io.sultanov
marvel
1.0.0-beta

Marvel Api
Learn Project

2022-05-30 18:13 UTC, ssstoyanov commented on pom.xml
> +            <version>2.7.0</version>
нет необходимости указывать версию, она уже указан в родителе

2022-05-30 18:13 UTC, ssstoyanov commented on pom.xml
> +            <plugin>
где плагин для ломбока?

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/api/controllers/CharacterController.java
> +    @GetMapping("/")
produces = application/json и дальше везде

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/api/controllers/CharacterController.java
> +    @PostMapping("/post")
consumes = application/json

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/api/controllers/ComicController.java
> +    @PostMapping("/post")
надо просто "", без пути, consumes так же не забудь

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/domain/characters/Character.java
> +    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE,
Почему тут такая каскадность?

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/domain/characters/CharacterService.java
> +        return characterRepository.findById(id).orElseThrow(RuntimeException::new);
https://github.com/pestrikv/marvel-api/pull/1#discussion_r885017528

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/domain/comics/Comic.java
> +    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE,
зачем такая каскадность?

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/domain/comics/Comic.java
> +    public void addToComicsCharacter(Character character) {
не нужно

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/domain/characters/Character.java
> +        comics.add(comic);
не нужно

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/domain/comics/Comic.java
> +    public Comic() {
не нужно

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/domain/comics/Comic.java
> +    public Comic(String name) {
не нужно

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/domain/comics/ComicRepository.java
> +@Repository
не нужно
https://github.com/pestrikv/marvel-api/pull/1#discussion_r885017779

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/domain/comics/ComicService.java
> +       return comicRepository.findById(id).orElseThrow(RuntimeException::new);
https://github.com/pestrikv/marvel-api/pull/1#discussion_r885017856

2022-05-30 18:13 UTC, ssstoyanov commented on src/main/java/com/example/marvel/domain/comics/ComicService.java
> +        return characterRepository.findAllById(Collections.singleton(id));
а? в чем смысл запроса?

2022-05-31 02:13 UTC, yergoff commented on src/main/java/com/example/marvel/domain/comics/ComicService.java
> +        return characterRepository.findAllById(Collections.singleton(id));
там надо было найти всех персонажей из определенного комикса, я особо пока не вникал как это сделать и чтоб красным не горело примерную строчку написал

2022-05-31 08:16 UTC, yergoff commented on src/main/java/com/example/marvel/domain/characters/Character.java
> +    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE,
а это я в курсе где-то подсмотрел, что если поставить каскадность на ALL, то при удалении одного комикса например все связанные с ним персонажи удалятся (вроде бы так)

2022-06-24 07:49 UTC, merged